version: '1.0'
name: loomloom-cli-release
displayName: LoomLoom-CLI-Release
triggers:
  trigger: auto
  push:
    tags:
      include:
        - ^v.*
        - ^gitee-release-test\..*
variables:
  global:
    - LOOMLOOM_GITEE_TOKEN
stages:
  - name: release
    displayName: Release
    strategy: naturally
    trigger: auto
    steps:
      - step: build@golang
        name: build_and_publish_gitee_release
        displayName: Build and Publish Gitee Release
        golangVersion: 1.24
        commands:
          - |
            set -e
            bash scripts/ci-release-gitee.sh
        artifacts:
          - name: LOOMLOOM_CLI_RELEASE
            path:
              - release
              - .release-tag
        caches:
          - /go/pkg/mod
